export const HANDEL_SEARCH_TERM = 'HANDEL_SEARCH_TERM'

export const REQUEST_BRANCH_PENDING = 'REQUEST_BRANCH_PENDING'
export const REQUEST_BRANCH_SUCCESS = 'REQUEST_BRANCH_SUCCESS'
export const REQUEST_BRANCH_FAILED = 'REQUEST_BRANCH_FAILED'